spring:
  activemq:
    packages:
      trust-all: true
    #in-memory: true
    user: admin
    password: admin
    broker-url: tcp://localhost:61616

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
